// Code generated by scripts/generate-domains.go. DO NOT EDIT.
// Generated from .specs/index.json version: 1.0.30
//
// This file is automatically regenerated when upstream specs change.
// To update domain aliases or deprecations, edit .specs/domain_config.yaml
//
// IMPORTANT: This file only defines DomainRegistry and AliasRegistry.
// Helper functions (ResolveDomain, GetDomainInfo, AllDomains) are in domains.go

package types

// DomainRegistry maps canonical domain names to metadata
// This is auto-generated from upstream specs on each build
var DomainRegistry = map[string]*DomainInfo{
	"admin_console_and_ui": {
		Name:        "admin_console_and_ui",
		DisplayName: "Admin Console And Ui",
		Description: "F5 Distributed Cloud Admin Console And Ui API specifications",
		Aliases:     []string{  },
	},
	"api": {
		Name:        "api",
		DisplayName: "Api",
		Description: "F5 Distributed Cloud Api API specifications",
		Aliases:     []string{  },
	},
	"app_firewall": {
		Name:        "app_firewall",
		DisplayName: "App Firewall",
		Description: "F5 Distributed Cloud App Firewall API specifications",
		Aliases:     []string{  },
	},
	"application_firewall": {
		Name:        "application_firewall",
		DisplayName: "Application Firewall",
		Description: "F5 Distributed Cloud Application Firewall API specifications",
		Aliases:     []string{  },
	},
	"bigip": {
		Name:        "bigip",
		DisplayName: "Bigip",
		Description: "F5 Distributed Cloud Bigip API specifications",
		Aliases:     []string{  },
	},
	"bigip_integration": {
		Name:        "bigip_integration",
		DisplayName: "Bigip Integration",
		Description: "F5 Distributed Cloud Bigip Integration API specifications",
		Aliases:     []string{  },
	},
	"billing_and_usage": {
		Name:        "billing_and_usage",
		DisplayName: "Billing And Usage",
		Description: "F5 Distributed Cloud Billing And Usage API specifications",
		Aliases:     []string{  },
	},
	"blindfold": {
		Name:        "blindfold",
		DisplayName: "Blindfold",
		Description: "F5 Distributed Cloud Blindfold API specifications",
		Aliases:     []string{  },
	},
	"bot_and_threat_defense": {
		Name:        "bot_and_threat_defense",
		DisplayName: "Bot And Threat Defense",
		Description: "F5 Distributed Cloud Bot And Threat Defense API specifications",
		Aliases:     []string{  },
	},
	"cdn": {
		Name:        "cdn",
		DisplayName: "Cdn",
		Description: "F5 Distributed Cloud Cdn API specifications",
		Aliases:     []string{  },
	},
	"cdn_and_content_delivery": {
		Name:        "cdn_and_content_delivery",
		DisplayName: "Cdn And Content Delivery",
		Description: "F5 Distributed Cloud Cdn And Content Delivery API specifications",
		Aliases:     []string{  },
	},
	"certificates": {
		Name:        "certificates",
		DisplayName: "Certificates",
		Description: "F5 Distributed Cloud Certificates API specifications",
		Aliases:     []string{  },
	},
	"client_side_defense": {
		Name:        "client_side_defense",
		DisplayName: "Client Side Defense",
		Description: "F5 Distributed Cloud Client Side Defense API specifications",
		Aliases:     []string{  },
	},
	"cloud_infrastructure": {
		Name:        "cloud_infrastructure",
		DisplayName: "Cloud Infrastructure",
		Description: "F5 Distributed Cloud Cloud Infrastructure API specifications",
		Aliases:     []string{  },
	},
	"container_services": {
		Name:        "container_services",
		DisplayName: "Container Services",
		Description: "F5 Distributed Cloud Container Services API specifications",
		Aliases:     []string{  },
	},
	"customer_edge": {
		Name:        "customer_edge",
		DisplayName: "Customer Edge",
		Description: "F5 Distributed Cloud Customer Edge API specifications",
		Aliases:     []string{  },
	},
	"data_intelligence": {
		Name:        "data_intelligence",
		DisplayName: "Data Intelligence",
		Description: "F5 Distributed Cloud Data Intelligence API specifications",
		Aliases:     []string{  },
	},
	"ddos": {
		Name:        "ddos",
		DisplayName: "Ddos",
		Description: "F5 Distributed Cloud Ddos API specifications",
		Aliases:     []string{  },
	},
	"dns": {
		Name:        "dns",
		DisplayName: "Dns",
		Description: "F5 Distributed Cloud Dns API specifications",
		Aliases:     []string{  },
	},
	"dns_and_domain_management": {
		Name:        "dns_and_domain_management",
		DisplayName: "Dns And Domain Management",
		Description: "F5 Distributed Cloud Dns And Domain Management API specifications",
		Aliases:     []string{  },
	},
	"generative_ai": {
		Name:        "generative_ai",
		DisplayName: "Generative Ai",
		Description: "F5 Distributed Cloud Generative Ai API specifications",
		Aliases:     []string{  },
	},
	"infrastructure_protection": {
		Name:        "infrastructure_protection",
		DisplayName: "Infrastructure Protection",
		Description: "F5 Distributed Cloud Infrastructure Protection API specifications",
		Aliases:     []string{ "infraprot",  },
	},
	"kubernetes": {
		Name:        "kubernetes",
		DisplayName: "Kubernetes",
		Description: "F5 Distributed Cloud Kubernetes API specifications",
		Aliases:     []string{  },
	},
	"kubernetes_and_orchestration": {
		Name:        "kubernetes_and_orchestration",
		DisplayName: "Kubernetes And Orchestration",
		Description: "F5 Distributed Cloud Kubernetes And Orchestration API specifications",
		Aliases:     []string{  },
	},
	"marketplace": {
		Name:        "marketplace",
		DisplayName: "Marketplace",
		Description: "F5 Distributed Cloud Marketplace API specifications",
		Aliases:     []string{  },
	},
	"network": {
		Name:        "network",
		DisplayName: "Network",
		Description: "F5 Distributed Cloud Network API specifications",
		Aliases:     []string{  },
	},
	"network_connectivity": {
		Name:        "network_connectivity",
		DisplayName: "Network Connectivity",
		Description: "F5 Distributed Cloud Network Connectivity API specifications",
		Aliases:     []string{  },
	},
	"network_security": {
		Name:        "network_security",
		DisplayName: "Network Security",
		Description: "F5 Distributed Cloud Network Security API specifications",
		Aliases:     []string{  },
	},
	"nginx_one": {
		Name:        "nginx_one",
		DisplayName: "Nginx One",
		Description: "F5 Distributed Cloud Nginx One API specifications",
		Aliases:     []string{  },
	},
	"object_storage": {
		Name:        "object_storage",
		DisplayName: "Object Storage",
		Description: "F5 Distributed Cloud Object Storage API specifications",
		Aliases:     []string{  },
	},
	"observability": {
		Name:        "observability",
		DisplayName: "Observability",
		Description: "F5 Distributed Cloud Observability API specifications",
		Aliases:     []string{ "obs", "o11y",  },
	},
	"observability_and_analytics": {
		Name:        "observability_and_analytics",
		DisplayName: "Observability And Analytics",
		Description: "F5 Distributed Cloud Observability And Analytics API specifications",
		Aliases:     []string{  },
	},
	"other": {
		Name:        "other",
		DisplayName: "Other",
		Description: "F5 Distributed Cloud Other API specifications",
		Aliases:     []string{  },
	},
	"rate_limiting": {
		Name:        "rate_limiting",
		DisplayName: "Rate Limiting",
		Description: "F5 Distributed Cloud Rate Limiting API specifications",
		Aliases:     []string{  },
	},
	"service_mesh": {
		Name:        "service_mesh",
		DisplayName: "Service Mesh",
		Description: "F5 Distributed Cloud Service Mesh API specifications",
		Aliases:     []string{ "mesh",  },
	},
	"shape": {
		Name:        "shape",
		DisplayName: "Shape",
		Description: "F5 Distributed Cloud Shape API specifications",
		Aliases:     []string{  },
	},
	"site": {
		Name:        "site",
		DisplayName: "Site",
		Description: "F5 Distributed Cloud Site API specifications",
		Aliases:     []string{  },
	},
	"site_management": {
		Name:        "site_management",
		DisplayName: "Site Management",
		Description: "F5 Distributed Cloud Site Management API specifications",
		Aliases:     []string{  },
	},
	"statistics": {
		Name:        "statistics",
		DisplayName: "Statistics",
		Description: "F5 Distributed Cloud Statistics API specifications",
		Aliases:     []string{  },
	},
	"support": {
		Name:        "support",
		DisplayName: "Support",
		Description: "F5 Distributed Cloud Support API specifications",
		Aliases:     []string{  },
	},
	"system": {
		Name:        "system",
		DisplayName: "System",
		Description: "F5 Distributed Cloud System API specifications",
		Aliases:     []string{  },
	},
	"telemetry_and_insights": {
		Name:        "telemetry_and_insights",
		DisplayName: "Telemetry And Insights",
		Description: "F5 Distributed Cloud Telemetry And Insights API specifications",
		Aliases:     []string{  },
	},
	"threat_campaign": {
		Name:        "threat_campaign",
		DisplayName: "Threat Campaign",
		Description: "F5 Distributed Cloud Threat Campaign API specifications",
		Aliases:     []string{  },
	},
	"user_and_account_management": {
		Name:        "user_and_account_management",
		DisplayName: "User And Account Management",
		Description: "F5 Distributed Cloud User And Account Management API specifications",
		Aliases:     []string{  },
	},
	"users": {
		Name:        "users",
		DisplayName: "Users",
		Description: "F5 Distributed Cloud Users API specifications",
		Aliases:     []string{  },
	},
	"virtual": {
		Name:        "virtual",
		DisplayName: "Virtual",
		Description: "F5 Distributed Cloud Virtual API specifications",
		Aliases:     []string{  },
	},
	"virtual_server": {
		Name:        "virtual_server",
		DisplayName: "Virtual Server",
		Description: "F5 Distributed Cloud Virtual Server API specifications",
		Aliases:     []string{  },
	},
	"vpm_and_node_management": {
		Name:        "vpm_and_node_management",
		DisplayName: "Vpm And Node Management",
		Description: "F5 Distributed Cloud Vpm And Node Management API specifications",
		Aliases:     []string{  },
	},
}

// AliasRegistry maps aliases and canonical names to canonical names
// Initialized by init() in domains.go
var AliasRegistry = map[string]string{}
